version: '3'
networks:
  docker_network:
    driver: bridge
services:
  libpostal:
    image: pelias/libpostal-service
    container_name: pelias_libpostal
    user: "${DOCKER_USER}"
    restart: always
    ports: [ "4400:4400" ]
    networks:
      - docker_network
  schema:
    image: pelias/schema:master
    container_name: pelias_schema
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json:z"
    networks:
      - docker_network
  api:
    image: pelias/api:master
    container_name: pelias_api
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=4000" ]
    ports: [ "4000:4000" ]
    networks:
      - docker_network
    volumes:
      - "./pelias.json:/code/pelias.json:z"
  placeholder:
    image: pelias/placeholder:master
    container_name: pelias_placeholder
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=4100" ]
    ports: [ "4100:4100" ]
    networks:
      - docker_network
    volumes:
      - "./pelias.json:/code/pelias.json:z"
      - "${DATA_DIR}:/data:z"
      - "./blacklist/:/data/blacklist:z"
  whosonfirst:
    image: pelias/whosonfirst:master
    container_name: pelias_whosonfirst
    user: "${DOCKER_USER}"
    networks:
      - docker_network
    volumes:
      - "./pelias.json:/code/pelias.json:z"
      - "${DATA_DIR}:/data:z"
      - "./blacklist/:/data/blacklist:z"
  openstreetmap:
    image: pelias/openstreetmap:master
    container_name: pelias_openstreetmap
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json:z"
      - "${DATA_DIR}:/data:z"
      - "./blacklist/:/data/blacklist:z"
  openaddresses:
    image: pelias/openaddresses:master
    container_name: pelias_openaddresses
    user: "${DOCKER_USER}"
    networks:
      - docker_network
    volumes:
      - "./pelias.json:/code/pelias.json:z"
      - "${DATA_DIR}:/data:z"
      - "./blacklist/:/data/blacklist:z"
  transit:
    image: pelias/transit:master
    container_name: pelias_transit
    user: "${DOCKER_USER}"
    networks:
      - docker_network
    volumes:
      - "./pelias.json:/code/pelias.json:z"
      - "${DATA_DIR}:/data:z"
  csv-importer:
    image: pelias/csv-importer:master
    container_name: pelias_csv_importer
    user: "${DOCKER_USER}"
    networks:
      - docker_network
    volumes:
      - "./pelias.json:/code/pelias.json:z"
      - "${DATA_DIR}:/data:z"
      - "./blacklist/:/data/blacklist:z"
  polylines:
    image: pelias/polylines:master
    container_name: pelias_polylines
    user: "${DOCKER_USER}"
    networks:
      - docker_network
    volumes:
      - "./pelias.json:/code/pelias.json:z"
      - "${DATA_DIR}:/data:z"
  interpolation:
    image: pelias/interpolation:master
    container_name: pelias_interpolation
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=4300" ]
    ports: [ "4300:4300" ]
    networks:
      - docker_network
    volumes:
      - "./pelias.json:/code/pelias.json:z"
      - "${DATA_DIR}:/data:z"
  pip:
    image: pelias/pip-service:master
    container_name: pelias_pip-service
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=4200" ]
    ports: [ "4200:4200" ]
    networks:
      - docker_network
    volumes:
      - "./pelias.json:/code/pelias.json:z"
      - "${DATA_DIR}:/data:z"
  elasticsearch:
    image: pelias/elasticsearch:7.5.1
    container_name: pelias_elasticsearch
    user: "${DOCKER_USER}"
    restart: always
    expose:
      - "9200"
      - "9300"
    ports: [ "9200:9200", "9300:9300" ]
    volumes:
      - "${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data:z"
    networks:
      - docker_network
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: [ "IPC_LOCK" ]
  fuzzy-tester:
    image: pelias/fuzzy-tester:master
    container_name: pelias_fuzzy_tester
    user: "${DOCKER_USER}"
    restart: "no"
    networks:
      - docker_network
    command: "--help"
    volumes:
      - "./pelias.json:/code/pelias.json:z"
      - "./test_cases:/code/pelias/fuzzy-tester/test_cases:z"
